import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "./storeProvider";
import Header from "../components/Header";
import ToastManager from "../components/ToastManager";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "NextJS Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <ToastContainer position="top-right" autoClose={5000} closeOnClick />
          <ToastManager />
          <Header />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
